CREATE TABLE IF NOT EXISTS PLAYERS (
	PLAYER_NO   BIGINT       NOT NULL AUTO_INCREMENT,
	NICK        VARCHAR(40)  NOT NULL,
	IP          VARCHAR(255) NOT NULL,
	CREATED_AT  DATETIME     NOT NULL,

	PRIMARY KEY(PLAYER_NO)
);

INSERT INTO PLAYERS ( NICK, IP, CREATED_AT ) VALUES ( 'npc', '127.0.0.1', now() );